baseURL = "https://tranhien.ooo"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "A littel bit of my life"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-123456789-1"
disqusShortname = "yourdiscussshortname"


[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "CẢNH BÁO: Đây chỉ là nơi mình ghi lại những kiến thức mới, để để tổng hợp, xem lại khi cần, nhưng gì mình nghĩ cần ghi nhớ theo quan điểm riêng của mình, không mang tính hướng giới thiệu hay hướng dẫn hihi."
  homeMetaContent = "Mình coi đây như nơi để ghi chú những thứ hay ho trong quá trình mình học và làm :D"
  footer = "A little bit of my life"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "someUser"
  fontHeader = 'Saira Semi Condensed'


[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
