baseURL = "https://pinkykitten.github.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "A littel bit of my life"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-123456789-1"
disqusShortname = "yourdiscussshortname"


[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  posts = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "Mình tập tành viết blog nên ko biết giật tít le thế nào cả :D"
  footer = "A little bit of my life"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "someUser"
  fontHeader = 'Saira Semi Condensed'


[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.nav]]
    name = "Categories"
    url = "/categories/"
    weight = 3
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
